spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/herfadb
#    username: springstudent
#    password: springstudent
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10

    url: jdbc:mysql://ballast.proxy.rlwy.net:47709/railway?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: LUKgITJRDcdSrWxDfbreGBJMAPrCAhra
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    maximum-pool-size: 10
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
  websocket:
    sockjs:
      suppress-origin-check: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: mf7373057@gmail.com
    password: cfhhrlxyhiikbucn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB




application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

server:
  port: 9994

encryption:
  salt:
    rounds: 10

jwt:
  algorithm:
    key: SuperSecureSecretKey
  issuer: "eCommerce"
  expiryInSeconds: 604800




project:
  poster: ${user.home}/poster/

base:
  url: "http://localhost:${server.port}"


STRIPE_SECRET_KEY:
  sk_test_51RLL9FE2kb6bjtHxTamrhWhodYcsa9FBQTSUpOXjvt9uKMTCunNDc0VyR0DwoKuBahjOudcQdmtVkGZYBcWCsklJ00cuQeI9lG
STRIPE_WEBHOOK_SECRET:
  whsec_296aaf1f43d3c2d5c388fa1241c581869aca15478ee2f1dfd2b858c6aad505ab
