spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/herfa_db
#    username: root
#    password: hanona
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
  datasource:
    url: jdbc:mysql://trolley.proxy.rlwy.net:53734/railway?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: YLWYGTCfWdSDOnLnbshXkgvKOQTNPUOA
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: mf7373057@gmail.com  # Your full email address
    password: cfhhrlxyhiikbucn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB



application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

server:
  port: 9994

encryption:
  salt:
    rounds: 10

jwt:
  algorithm:
    key: SuperSecureSecretKey
  issuer: "eCommerce"
  expiryInSeconds: 604800

project:
  poster: poster/

base:
  url: "http://localhost:9292"





#  user
#  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9:
#    eyJST0xFIjoiVVNFUiIsImlzcyI6ImVDb21tZXJjZSIsIlVTRVJOQU1FIjoic2FpMjUzMzJtZWQiLCJleHAiOjE3NDU5NjM4MTJ9:
#      JLsMWo19kr0EV5bnjLgfjZsZYFrn1MDyxDKENhl0xqU:

#merchant
#eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9:
#  eyJST0xFIjoiTUVSQ0hBTlQiLCJpc3MiOiJlQ29tbWVyY2UiLCJVU0VSTkFNRSI6InNhaTUzMzJtZWQiLCJleHAiOjE3NDU5NjM5NzF9:
#    RjKQW19TaRVWbbmSiCuc-i-dPwmrcgDOOGegoRNrCRw:

