spring:
  datasource:
    url: jdbc:mysql://switchback.proxy.rlwy.net:30279/railway
    username: root
    password: FdZaYjZxaDbynAHDmIoreGsCPzmVRxhl
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mf7373057@gmail.com
    password: otjleefjszgzecqc

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

server:
  port: 9990

encryption:
  salt:
    rounds: 10

jwt:
  algorithm:
    key: SuperSecureSecretKey
  issuer: "eCommerce"
  expiryInSeconds: 604800

project:
  poster: poster/

base:
  url: "http://localhost:9292"
