spring:
  datasource:
    url: jdbc:mysql://localhost:3306/herfadb
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

server:
  port: 9999

encryption:
  salt:
    rounds: 10

jwt:
  algorithm:
    key: SuperSecureSecretKey
  issuer: "eCommerce"
  expiryInSeconds: 604800

project:
  poster: poster/

base:
  url: "http://localhost:9292"
